GET http://localhost:3010

####
POST http://localhost:3010/createUsers
Content-Type: application/json


{
    "firstName":"Carlo",
    "lastName": "Atripla",
    "email":"carloatrica@gmail.com",
    "password":"ciccio",
    "age":"30"
}

####
POST http://localhost:3010/login 
Content-Type: application/json


{
 
    "email":"carloatrica@gmail.com",
    "password":"ciccio",
    
}